from typing import Optional, Dict
from datetime import datetime

from app.services.crud_keyword import keyword as keyword_crud
from app.services.crud_user import user as user_crud
from app.schemas_db.keyword import Keyword
from app.schemas_db.user import User, KeywordProgress

class KeywordService:
    async def get_keyword(self, keyword_key: str) -> Optional[dict]:
        """
        Retrieves keyword data. Returns dict to be JSON serializable for Agent.
        """
        kw = await keyword_crud.get_by_key(keyword_key)
        if kw:
            return kw.model_dump()
        return None

    async def create_keyword(self, data: dict) -> dict:
        """
        Creates a new keyword entry from data (e.g. generated by Tutor).
        Ensures `keyword_key` is set.
        """
        if "keyword" in data and "keyword_key" not in data:
            data["keyword_key"] = data["keyword"]
            
        # Pydantic validation via CRUD
        # CRUDBase expects Pydantic model or dict. 
        # If dict has extra fields, Pydantic (if configured) ignores them.
        created = await keyword_crud.create(data)
        return created.model_dump()

    async def update_user_star(self, user_id: str, keyword_key: str, result: dict) -> bool:
        """
        Updates user's mastery for the given keyword based on quiz result.
        Returns if passed.
        """
        user = await user_crud.get_by_email(user_id)
        if not user:
            return False
            
        # Get existing progress or default
        progress = user.keyword_progress.get(keyword_key, KeywordProgress())
        
        # Update Stats
        progress.last_reviewed_at = datetime.utcnow()
        score_gain = result.get("score", 0)
        is_passed = result.get("is_passed", False)
        
        if is_passed:
            # Star Rating Logic (Simple Heuristic for v1.1)
            # Evaluation Model determines the star rating (1~3)
            earned_star = result.get("star", 0) # Default to 0 if not provided
            
            # Keep the highest star rating achieved
            if earned_star > progress.star:
                progress.star = earned_star
        
        # Update User object in memory then save
        user.keyword_progress[keyword_key] = progress
        
        # Convert all to dicts for Mongo storage
        keyword_progress_dict = {k: v.model_dump() for k, v in user.keyword_progress.items()}
        
        # Persist to DB
        await user_crud.update(user.id, {"keyword_progress": keyword_progress_dict})
        
        return is_passed

    async def mark_learning_started(self, user_id: str, keyword_key: str) -> None:
        """
        Marks a keyword as 'attempted' (star=0) by the user.
        If progress already exists, it does nothing (preserves existing stars).
        """
        user = await user_crud.get_by_email(user_id)
        if not user:
            return
            
        # 이미 학습 기록이 있으면 건너뜀 (별점 유지)
        if keyword_key in user.keyword_progress:
            return
            
        # 없으면 초기화 (Star=0)
        progress = KeywordProgress(
            star=0,
            last_reviewed_at=datetime.utcnow()
        )
        
        user.keyword_progress[keyword_key] = progress
        
        # DB 저장
        keyword_progress_dict = {k: v.model_dump() for k, v in user.keyword_progress.items()}
        await user_crud.update(user.id, {"keyword_progress": keyword_progress_dict})

keyword_service = KeywordService()
