from typing import Optional, Dict
from datetime import datetime

from app.services.crud_keyword import keyword as keyword_crud
from app.services.crud_user import user as user_crud
from app.schemas_db.keyword import Keyword
from app.schemas_db.user import User, KeywordProgress

class KeywordService:
    async def get_keyword(self, keyword_key: str) -> Optional[dict]:
        """
        Retrieves keyword data. Returns dict to be JSON serializable for Agent.
        """
        kw = await keyword_crud.get_by_key(keyword_key)
        if kw:
            return kw.model_dump()
        return None

    async def create_keyword(self, data: dict) -> dict:
        """
        Creates a new keyword entry from data (e.g. generated by Tutor).
        Ensures `keyword_key` is set.
        """
        if "keyword" in data and "keyword_key" not in data:
            data["keyword_key"] = data["keyword"]
            
        # Pydantic validation via CRUD
        # CRUDBase expects Pydantic model or dict. 
        # If dict has extra fields, Pydantic (if configured) ignores them.
        created = await keyword_crud.create(data)
        return created.model_dump()

    async def update_user_mastery(self, user_id: str, keyword_key: str, result: dict) -> bool:
        """
        Updates user's mastery for the given keyword based on quiz result.
        Returns if passed.
        """
        user = await user_crud.get(user_id)
        if not user:
            return False
            
        # Get existing progress or default
        progress = user.keyword_progress.get(keyword_key, KeywordProgress())
        
        # Update Stats
        progress.last_reviewed_at = datetime.utcnow()
        score_gain = result.get("score", 0)
        is_passed = result.get("is_passed", False)
        
        if is_passed:
            progress.successful_attempts += 1
            progress.score += (score_gain * 0.1) # Simple increment heuristic
            
            # Simple Level Logic: 
            # 0->1: 1 success. 1->2: 3 successes. etc.
            if progress.level == 0:
                progress.level = 1
            elif progress.level == 1 and progress.successful_attempts >= 3:
                progress.level = 2
        
        # Update User object in memory then save
        user.keyword_progress[keyword_key] = progress
        
        # Convert all to dicts for Mongo storage
        keyword_progress_dict = {k: v.model_dump() for k, v in user.keyword_progress.items()}
        
        # Persist to DB
        await user_crud.update(user_id, {"keyword_progress": keyword_progress_dict})
        
        return is_passed

keyword_service = KeywordService()
